-- Create a table for site-wide settings
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default keys if they don't exist
INSERT INTO site_settings (key, value, description)
VALUES 
  ('facebook_pixel_id', '', 'Facebook Pixel ID for tracking'),
  ('tiktok_pixel_id', '', 'TikTok Pixel ID for tracking')
ON CONFLICT (key) DO NOTHING;

-- Enable Row Level Security
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts when re-running
DROP POLICY IF EXISTS "Allow public read access to settings" ON site_settings;
DROP POLICY IF EXISTS "Allow authenticated update access to settings" ON site_settings;

-- Allow everyone to read settings (Essential for frontend pixel loading)
CREATE POLICY "Allow public read access to settings" 
ON site_settings FOR SELECT 
USING (true);

-- Allow authenticated users to update (Essential for Admin Dashboard)
CREATE POLICY "Allow authenticated update access to settings" 
ON site_settings FOR UPDATE 
USING (auth.role() = 'authenticated');

-- Grant access to public role just in case
GRANT SELECT ON site_settings TO anon;
GRANT SELECT ON site_settings TO authenticated;
GRANT UPDATE ON site_settings TO authenticated;
