import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Tables, TablesInsert, TablesUpdate, Enums } from '@/integrations/supabase/types';

export type Order = Tables<'orders'>;
export type OrderItem = Tables<'order_items'>;
export type OrderStatus = Enums<'order_status'>;
export type DeliveryType = Enums<'delivery_type'>;

export type OrderWithItems = Order & {
  items: OrderItem[];
};

export function useOrders({ 
  page, 
  pageSize = 20,
  searchQuery,
  status,
  deliveryType,
  wilaya,
  store,
  fromDate,
  toDate,
}: { 
  page: number, 
  pageSize?: number,
  searchQuery?: string,
  status?: string,
  deliveryType?: string,
  wilaya?: string,
  store?: string,
  fromDate?: string,
  toDate?: string,
}) {
  return useQuery({
    queryKey: ['orders', { page, pageSize, searchQuery, status, deliveryType, wilaya, store, fromDate, toDate }],
    queryFn: async () => {
      const from = (page - 1) * pageSize;
      const to = from + pageSize - 1;

      let query = supabase
        .from('orders')
        .select(`
          *,
          items:order_items(
            *,
            products(name_ar, name_fr)
          )
        `);

      if (searchQuery) {
        query = query.or(`order_number.ilike.%${searchQuery}%,customer_name.ilike.%${searchQuery}%,customer_phone.ilike.%${searchQuery}%`);
      }
      if (status && status !== 'all') {
        query = query.eq('status', status);
      }
      if (deliveryType && deliveryType !== 'all') {
        query = query.eq('delivery_type', deliveryType);
      }
      if (wilaya && wilaya !== 'all') {
        query = query.eq('wilaya_name', wilaya);
      }
      if (store && store !== 'all') {
        query = query.eq('send_from_store', store);
      }
      if (fromDate) {
        query = query.gte('created_at', fromDate);
      }
      if (toDate) {
        query = query.lte('created_at', toDate);
      }

      const { data, error, count } = await query
        .order('created_at', { ascending: false })
        .range(from, to);

      if (error) throw error;
      
      return { data: data as OrderWithItems[], count };
    },
  });
}

export function useOrder(id: string | undefined) {
  return useQuery({
    queryKey: ['order', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          items:order_items(*)
        `)
        .eq('id', id)
        .maybeSingle();

      if (error) throw error;
      return data as OrderWithItems | null;
    },
    enabled: !!id,
  });
}

export function useOrdersByDateRange(from: Date, to: Date) {
  return useQuery({
    queryKey: ['orders', { from, to }],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          items:order_items(*)
        `)
        .gte('created_at', from.toISOString())
        .lte('created_at', to.toISOString())
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as OrderWithItems[];
    },
  });
}

export function useCreateOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: {
      order: Omit<TablesInsert<'orders'>, 'order_number'>;
      items: Omit<TablesInsert<'order_items'>, 'order_id'>[];
    }) => {
      const MAX_RETRIES = 3;
      let lastError: any = null;

      for (let i = 0; i < MAX_RETRIES; i++) {
        try {
          // Create order (order_number is auto-generated by trigger)
          const { data: order, error } = await supabase
            .from('orders')
            .insert(data.order) // order_number is intentionally not sent, so trigger can set it
            .select()
            .single();

          if (error) {
            throw error; // Re-throw other errors
          }

          // Create order items
          const itemsToInsert = data.items.map(item => ({
            ...item,
            order_id: order.id,
          }));

          const { error: itemsError } = await supabase
            .from('order_items')
            .insert(itemsToInsert);

          if (itemsError) throw itemsError;

          return order; // Order and items created successfully
        } catch (error) {
          lastError = error;
          if (error && typeof error === 'object' && 'code' in error && error.code === '23505' && error.message.includes('orders_order_number_key')) {
            console.warn(`Duplicate order number detected, retrying... (${i + 1}/${MAX_RETRIES})`);
            await new Promise(resolve => setTimeout(resolve, 500 * (i + 1))); // Exponential backoff
            continue; // Try again
          }
          throw error; // Re-throw other errors
        }
      }
      
      // If all retries fail, throw the last error
      if (lastError) {
        throw lastError;
      }
      throw new Error("Order creation failed after multiple retries due to unknown error.");
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useUpdateOrderStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: OrderStatus }) => {
      const { error } = await supabase
        .from('orders')
        .update({ status })
        .eq('id', id);

      if (error) throw error;
      return id;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useBulkUpdateOrderStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ ids, status }: { ids: string[]; status: OrderStatus }) => {
      const { error } = await supabase
        .from('orders')
        .update({ status })
        .in('id', ids);

      if (error) throw error;
      return ids;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useDeleteOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      // Order items are deleted via CASCADE
      const { error } = await supabase.from('orders').delete().eq('id', id);
      if (error) throw error;
      return id;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useBulkDeleteOrders() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (ids: string[]) => {
      const { error } = await supabase
        .from('orders')
        .delete()
        .in('id', ids);

      if (error) throw error;
      return ids;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}
