// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orfxjmoyjuonebhcxsja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZnhqbW95anVvbmViaGN4c2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MzE4NTAsImV4cCI6MjA4NDEwNzg1MH0.4OXytsN_89Jo-SQ0-SDoimXYd0K_BkSBLbTrXon0aTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});